package com.codekrypt.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.codekrypt.greendao.db.LOG;

import com.codekrypt.greendao.db.LOGDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lOGDaoConfig;

    private final LOGDao lOGDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lOGDaoConfig = daoConfigMap.get(LOGDao.class).clone();
        lOGDaoConfig.initIdentityScope(type);

        lOGDao = new LOGDao(lOGDaoConfig, this);

        registerDao(LOG.class, lOGDao);
    }
    
    public void clear() {
        lOGDaoConfig.getIdentityScope().clear();
    }

    public LOGDao getLOGDao() {
        return lOGDao;
    }

}
